# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-16 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking_tb',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('did', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('hid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('hosp_name', models.CharField(max_length=50)),
                ('dr_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('cart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('med_name', models.CharField(max_length=50)),
                ('phar_id', models.IntegerField()),
                ('phar_name', models.CharField(max_length=50)),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chat_tb',
            fields=[
                ('chatid', models.IntegerField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=30)),
                ('did', models.IntegerField()),
                ('time', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('message', models.TextField()),
                ('lid', models.IntegerField()),
                ('utype', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='diseasetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=200)),
                ('symptom1', models.CharField(max_length=200)),
                ('symptom2', models.CharField(max_length=200)),
                ('symptom3', models.CharField(max_length=200)),
                ('symptom4', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_regis',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False)),
                ('lid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('hid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='feedbacktable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('lid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hosptital_regis',
            fields=[
                ('hid', models.IntegerField(primary_key=True, serialize=False)),
                ('lid', models.IntegerField()),
                ('hosp_nm', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('contct_persn', models.CharField(max_length=30)),
                ('contct_no', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='lab_bking',
            fields=[
                ('labbk_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lab_id', models.IntegerField()),
                ('lid', models.IntegerField()),
                ('test_nms', models.CharField(max_length=150)),
                ('bk_time', models.CharField(max_length=30)),
                ('lab_nm', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('notifica', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='lab_regis',
            fields=[
                ('lab_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lid', models.IntegerField()),
                ('lab_nm', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='login_tb',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('usertype', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='med_cat',
            fields=[
                ('med_cid', models.IntegerField(primary_key=True, serialize=False)),
                ('med_cnm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='medicine_tb',
            fields=[
                ('med_id', models.IntegerField(primary_key=True, serialize=False)),
                ('med_cid', models.IntegerField()),
                ('med_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=550)),
                ('phar_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='msgtb',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('frm_id', models.CharField(max_length=50)),
                ('to_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='odr_delivry',
            fields=[
                ('odr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lid', models.IntegerField()),
                ('ful_name', models.CharField(max_length=50)),
                ('ph_no', models.IntegerField()),
                ('pay_typ', models.CharField(max_length=30)),
                ('addres', models.TextField()),
                ('billno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='odr_details',
            fields=[
                ('ord_dt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lid', models.IntegerField()),
                ('billno', models.IntegerField()),
                ('med_name', models.CharField(max_length=50)),
                ('phar_id', models.IntegerField()),
                ('phar_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='patient_regis',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('lid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('ph_no', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacy_tb',
            fields=[
                ('phar_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phar_name', models.CharField(max_length=50)),
                ('hid', models.IntegerField()),
                ('lid', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='prescriptiontable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('prescription', models.CharField(max_length=200)),
                ('pharmacy', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('userid', models.IntegerField(default=0)),
                ('place', models.CharField(default='0', max_length=200)),
                ('phone', models.IntegerField(default=0)),
                ('name', models.CharField(default='0', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='testtb',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('tstname', models.CharField(max_length=50)),
                ('lab_id', models.IntegerField()),
            ],
        ),
    ]
