# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-03 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newtesttb',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('tstname', models.CharField(max_length=50)),
                ('pid', models.IntegerField()),
                ('lab_id', models.IntegerField()),
            ],
        ),
    ]
