# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-03 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_newtesttb'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtesttb',
            name='dates',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='newtesttb',
            name='res',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
