# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-10 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200303_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='out_hosptital_regis',
            fields=[
                ('hid', models.IntegerField(primary_key=True, serialize=False)),
                ('lid', models.IntegerField()),
                ('hosp_nm', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('contct_persn', models.CharField(max_length=30)),
                ('contct_no', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
