# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-10 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20200310_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='out_lab_regis',
            fields=[
                ('lab_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lid', models.IntegerField()),
                ('lab_nm', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='out_pharmacy_tb',
            fields=[
                ('phar_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phar_name', models.CharField(max_length=50)),
                ('hid', models.IntegerField()),
                ('lid', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
