# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-10 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20200310_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='out_pharmacy_tb',
            name='password',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='out_pharmacy_tb',
            name='username',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
