# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-10 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20200310_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notname', models.CharField(max_length=50)),
                ('loc', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('pres', models.CharField(max_length=500)),
            ],
        ),
    ]
