# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-11 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_regis',
            name='bld',
            field=models.CharField(default='B +ve', max_length=30),
        ),
    ]
