# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-17 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_presctab'),
    ]

    operations = [
        migrations.CreateModel(
            name='labtesttab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('labid', models.IntegerField()),
                ('prdate', models.CharField(max_length=300)),
                ('tname', models.CharField(max_length=1000)),
                ('result', models.CharField(max_length=1000)),
                ('path', models.CharField(max_length=1000)),
            ],
        ),
    ]
