# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-17 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_labtesttab'),
    ]

    operations = [
        migrations.CreateModel(
            name='medpatients',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('medname', models.CharField(max_length=50)),
                ('times', models.CharField(max_length=50)),
                ('prdate', models.CharField(max_length=50)),
                ('noday', models.CharField(max_length=550)),
            ],
        ),
    ]
