# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-17 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_medpatients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medpatients',
        ),
    ]
