# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-17 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_delete_medpatients'),
    ]

    operations = [
        migrations.CreateModel(
            name='medpatients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('medname', models.CharField(max_length=50)),
                ('times', models.CharField(max_length=50)),
                ('prdate', models.CharField(max_length=50)),
                ('noday', models.CharField(max_length=550)),
                ('pharid', models.IntegerField(default=0)),
            ],
        ),
    ]
