# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-17 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_medpatients'),
    ]

    operations = [
        migrations.AddField(
            model_name='presctab',
            name='docname',
            field=models.CharField(default='Doc', max_length=300),
        ),
    ]
