# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-17 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_presctab_docname'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtesttab',
            name='labname',
            field=models.CharField(default='Lab', max_length=300),
        ),
    ]
